### ISSUE TITLE
Component styling affects other components

### ISSUE THREAD

**Issue by jamintz** [sickdyd/react-search-autocomplete#14]
Trying to add this to my site but the default styling it comes with is overriding and negatively affecting my existing styling. I'm using material-ui for other elements and styles.

**Comment by sickdyd** [comment]
Hello @jamintz! What version are you using? This bug should have been fixed in version `4.0.0`. [This was the issue.](https://github.com/sickdyd/react-search-autocomplete/issues/9). If you are using a prior version, try updating it. If you are using the latest version, can you create a [codesandbox](https://codesandbox.io/) with an example?

**Comment by sickdyd** [comment]
Closed because solved in version `4.0.0`
