### ISSUE TITLE
Add mic button

### ISSUE THREAD

**Issue by imdkbj** [sickdyd/react-search-autocomplete#35]
Hi, thnx for the beautiful library.

Kindly add a mic button and expected behaviour like as Google or expose a method to add a custom component.

**Comment by sickdyd** [comment]
@imdkbj Hello! What do you mean with "mic button"? Can you show me a screenshot?

**Comment by imdkbj** [comment]
Hey, mic to search by voice.

![IMG_20210828_095228.jpg](https://user-images.githubusercontent.com/46839821/131205973-b77728f5-9e87-473f-8003-abac62cac755.jpg)

**Comment by sickdyd** [comment]
@imdkbj Apologies, for the time being the search by voice feature is not going to be implemented since it would entail adding voice to text conversion libraries and I suspect a lot of extra work. Even adding just a component is not going to be easy, it would require a way to return the voice converted to text and "type" it in the search box... feel free to open a PR if you think you can do it!

If there is high demand for this I can consider looking into it more.

**Comment by imdkbj** [comment]
Thanks buddy for the reply. I will try to create a PR.

**Comment by sickdyd** [comment]
Issue closed because the feature entails too much work and doesn't seem like a popular request.
