### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by Eclipseop** [sickdyd/react-search-autocomplete#36]
Is there currently / will there be an effort to convert to typescript / adding a .d.ts?

**Comment by sickdyd** [comment]
@Eclipseop Hello! Definitiely it's in my plans. Right now I'm kind of busy with work so I don't have a date for this, but it's something I wanted to implement for a long time...

**Comment by sickdyd** [comment]
Closed and added request to todo list.

**Comment by sickdyd** [comment]
@Eclipseop TS was implemented in version 6.0.0!

**Comment by gignupg** [comment]
@sickdyd TS stopped working since version 7.0.0! You can also see this on NPM. Since version 7.0.0 the TS icon is missing:

![Screenshot from 2022-06-20 21-41-51](https://user-images.githubusercontent.com/52784332/174668768-9ca35641-83ea-4dc2-88e2-be7eda61f877.png)

![Screenshot from 2022-06-20 21-44-00](https://user-images.githubusercontent.com/52784332/174668794-efa1cf90-a188-4944-99dd-46c6e277022d.png)

**Comment by sickdyd** [comment]
@gignupg Fixed in the latest release!
